config/routes.rb
Rails.application.routes.draw do


  get 'home/index'
  root to: 'home#index'
  devise_for :trainers
  resources :trainers

  patch 'pokemons/capture', to: 'pokemons#capture', as: 'capture'
  patch 'pokemons/damage', to: 'pokemons#damage', as: 'damage'

  resources :pokemons
end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
	belongs_to :trainer
	validates :name, presence: true, uniqueness: true

end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
	has_many :pokemons
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    trainerless_pokemon = Pokemon.where(trainer:nil)
    @pokemon = trainerless_pokemon.sample
  end

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  
  def capture
    @pokemon = Pokemon.find(params[:id])
    @pokemon.trainer = current_trainer
    @pokemon.save
    redirect_to root_path
  end

  def damage
      @pokemon = Pokemon.find(params[:id])
      if @pokemon.health > 0
        @pokemon.health = @pokemon.health - 10
      else
        @pokemon.destroy
      end
      @pokemon.save
      redirect_to trainer_path(current_trainer)
  end

  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.health = 100
    @pokemon.level = 1
    @pokemon.trainer = current_trainer
    if @pokemon.save == false
      flash[:error] = @pokemon.errors.full_messages.to_sentence
      redirect_to new_pokemon_path
    else
      redirect_to trainer_path(current_trainer)
    end
    
    
  end

  def pokemon_params
    params.require(:pokemon).permit(:name)
  end

end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_filter :authenticate_trainer!

  def index
    @trainers = Trainer.all
  end

  def show
    @trainer = Trainer.find(params[:id])
    @trainer_pokemon = Pokemon.where(trainer_id:current_trainer)
    
    unless @trainer == current_trainer
      redirect_to :back, :alert => "Access denied."
    end
  end

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/home/index.html.erb
<h3>Welcome to PokePortal</h3>
<p><%= link_to 'Trainers:', trainers_path %> <%= Trainer.count %> registered</p>

<% if @pokemon and current_trainer %>
  <p> A wild <%= @pokemon.name %> has appeared!</p>
  <!-- REPLACE THIS LINE BELOW -->
  <%= button_to "Throw a Pokeball!", capture_path(id: @pokemon), :class => "button medium", :method => :patch %>
  
<% end %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'PokePortal Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if trainer_signed_in? %>
  <li><%= link_to 'Edit Your Trainer', edit_trainer_registration_path %></li>
  <li><%= link_to 'Log Out', destroy_trainer_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Log In', new_trainer_session_path %></li>
  <li><%= link_to 'Join PokePortal', new_trainer_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Railsdecal Proj1" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Railsdecal Proj1" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pokemons/create.html.erb
<h1>Pokemons#create</h1>
<p>Find me in app/views/pokemons/create.html.erb</p>

app/views/pokemons/destroy.html.erb
<h1>Pokemons#destroy</h1>
<p>Find me in app/views/pokemons/destroy.html.erb</p>

app/views/pokemons/edit.html.erb
<h1>Pokemons#edit</h1>
<p>Find me in app/views/pokemons/edit.html.erb</p>

app/views/pokemons/new.html.erb
<%= simple_form_for @pokemon do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/pokemons/show.html.erb
<h1>Pokemons#show</h1>
<p>Find me in app/views/pokemons/show.html.erb</p>

app/views/pokemons/update.html.erb
<h1>Pokemons#update</h1>
<p>Find me in app/views/pokemons/update.html.erb</p>

app/views/trainers/_trainer.html.erb
<td><%= link_to trainer.name, trainer %></td>
<td><%= link_to trainer.email, trainer %></td>

app/views/trainers/index.html.erb
<div class="container">
  <div class="row">
    <h3>Trainers</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @trainers.each do |trainer| %>
            <tr>
              <%= render trainer %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/trainers/show.html.erb
<h3>Trainer</h3>
<p>Name: <%= @trainer.name if @trainer.name %></p>
<p>Email: <%= @trainer.email if @trainer.email %></p>


<% @trainer_pokemon.each do |pokemon| %>
	<p>Name: <%= pokemon.name %>, Level: <%= pokemon.level %>, Health: <%= pokemon.health %></p>
	<%= button_to "Do Damage!", damage_path(id: pokemon), :class => "button medium", :method => :patch %>
<% end %>